version: '3'
services:
  mongo-db:
    image: mongo
    ports:
      - 27017:27017
  client-app:
    build: ./gomoku_react_frontend
    environment:
      - REACT_APP_PROXY_HOST=http://server-app:8080
    volumes:
    - ./gomoku_react_frontend/src:/gomoku_react_frontend/src
    - ./gomoku_react_frontend/public:/gomoku_react_frontend/public
    ports:
    - 3000:3000
  server-app:
    build: ./gomoku_backend
    environment:
      - dbURI=mongodb://mongo-db:27017
    volumes: 
    - ./gomoku_backend/src:/gomoku_backend/src
    ports: 
    - 8080:8080
