export { default as LoginPage } from './LoginPage'
export { default as Home } from './Home'
export { default as MainGame } from './MainGame'
export { default as GameLog } from './GameLog'
export { default as GameHistory } from './GameHistory'
export { default as SignUp } from './SignUpGame'